+debug

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -32,12 +32,6 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Check files
-        run: |
-          ls -la
-          ls -la swagger-coverage-output/ || echo "Directory not found"
-          test -f swagger-doc-dm-api-account.json || echo "Swagger file not found"
-
       - name: Run tests
         run: |
           export PATH=$JAVA_HOME/bin:$PATH
@@ -45,6 +39,13 @@ jobs:
           which java
           python -m pytest ./tests --alluredir=allure-results --disable-warnings
         continue-on-error: true
+
+      - name: Check files
+        run: |
+          ls -la
+          ls -la swagger-coverage-output/ || echo "Directory not found"
+          ls -la allure-results/ || echo "Directory not found"
+          test -f swagger-doc-dm-api-account.json || echo "Swagger file not found"
 
       - name: Run Coverage
         if: ${{ always()}}
